inotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('noteapp.urls'),name = 'noteapp')
]

noteapp/urls.py
from django.urls import path
from . import views
import django.contrib.auth.views as auth_views


app_name = 'noteapp'
urlpatterns = [
    path('',views.index,name = 'index'),
    path('login/',auth_views.LoginView.as_view(template_name = 'noteapp/login.html'),name = 'login'),
    path('logout/',auth_views.LogoutView.as_view(template_name = 'noteapp/loggedout.html'),name = 'logout'),
    path('register/',views.register,name = 'register'),
    path('settings/',views.settings,name = 'settings'),
    path('update/<int:id>/',views.update,name = 'update'),
    #path('loggedout/',views.loggedout,name = 'loggedout'),
    path('home/',views.home_page,name = 'home_page'),
    path('delete/<int:id>/',views.delete,name = 'delete'),
    # path('addnote/',views.addnote,name = 'addnote'),
]

noteapp/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime 
from django.utils import timezone
# Create your models here.

class Note(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    notes_title = models.CharField(max_length=200,null = False)
    note_text = models.TextField(null = False)
    Created_on = models.DateTimeField(auto_now_add=True )
    Last_Update_date = models.DateTimeField(auto_now= True,blank=True)
    def __str__(self):
        return self.notes_title
    def was_published_recently(self):
        return self.Created_on >= timezone.now() - datetime.timedelta(days=1)

noteapp/forms.py
from django import forms
from .models import Note
from django.contrib.auth.models import User

class NoteCreationForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['notes_title','note_text']

class NoteUpdateForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['notes_title','note_text']   

class AccountSettingsForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name']

noteapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

from django.contrib.auth.decorators import login_required
from .forms import NoteCreationForm,NoteUpdateForm,AccountSettingsForm
from .models import Note

# Create your views here.
@login_required
def home_page(request):
    #import ipdb;ipdb.set_trace()
    current_user = request.user
    user_id = current_user.id
    notes = Note.objects.filter(user__id = user_id)
    form = NoteCreationForm()
    if request.method == "POST":
        form = NoteCreationForm(request.POST)
        if form.is_valid():
            note_obj = form.save(commit=False)
            note_obj.user = request.user
            note_obj.save()

            return redirect('noteapp:home_page')

    context={
        'notes' : notes,
        'form' : form,
    }
    return render(request,'noteapp/home.html',context)

# def addnote(request):
#     form = NoteCreationForm()
#     if request.method == "POST":
#         form = NoteCreationForm(request.POST)
#         if form.is_valid():
#             note_obj = form.save(commit=False)
#             note_obj.user = request.user
#             note_obj.save()

#             return redirect('noteapp:home_page')
#     return render(request,'noteapp/addnote.html')   


def index(request):
    return render(request,'noteapp/index.html')

def loggedout(request):
    return render(request,'noteapp/loggedout.html')

# def login(request):
#     return render(request,'noteapp/login.html')

def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request,"Account Created Successfully")
            return redirect('noteapp:login')


    context ={
        'form':form
    }
    return render(request,'noteapp/register.html',context)

@login_required
def settings(request):
    user = request.user
    form = AccountSettingsForm(instance=user)
    if request.method == "POST":
        user.username = request.post["username"]
        user.first_name = request.post["first_name"]
        user.last_name = request.post["last_name"]

        user.save()
        messages.success(request,"Account Updated Successfully")
        
        return redirect("noteapp:settings")

    context={
        'form' : form,
        'user' : user,
    }
    return render(request,'noteapp/settings.html',context)

@login_required
def update(request,id):
    note_to_update = Note.objects.get(id=id)
    form = NoteUpdateForm(instance = note_to_update)

    if request.method == "POST":
        form = NoteUpdateForm(request.POST)
        if form.is_valid():
            note_to_update.notes_title = form.cleaned_data["notes_title"]
            note_to_update.note_text = form.cleaned_data["note_text"]

            note_to_update.save()

            return redirect('noteapp:home_page')
                
    context ={
        'note' : note_to_update,
        'form' : form
    }
    return render(request,'noteapp/update.html',context)

@login_required
def delete(request,id):
    note_to_delete = Note.objects.get(id=id)
    if request.method == "POST":
        note_to_delete.delete()
        return redirect('noteapp:home_page')
    
    return render(request,'noteapp/delete.html')

noteapp/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="{% static 'css/boostrap.min.css' %}">    <!-- CSS only -->
<link rel="stylesheet" href="{% static 'css/main.css' %}">    
<title>Inote</title>
</head>
<body>
    <header >
        <nav class="navbar navbar-expand navbar-dark bg-dark">
            <ul class="nav navbar-nav">
                
                {% if user.is_authenticated and not request.get_full_path == "/settings/"%}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'noteapp:home_page' %}">Inote</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link add" href="#">Add notes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link add" href="{% url 'noteapp:settings' %}">Settings</a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link add" href="{% url 'noteapp:logout' %}">Log Out</a>
                </li>
                    
                {% elif request.get_full_path == "/settings/" %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'noteapp:home_page' %}">Inote</span></a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link add" href="{% url 'noteapp:logout' %}">Log Out</a>
                    </li>

                {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'noteapp:index' %}">Inote</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link add" href="{% url 'noteapp:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link add" href="{% url 'noteapp:login' %}">Login</a>
                </li>
                {% endif %}                    
            </ul>
        </nav>
    </header>
    {% block  body%}
    {% endblock body%}
    <script src="{% static 'js/index.js' %}"> </script>
</body>
</html>    

noteapp/templates/noteapp/addnote.html
{% extends '../base/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="add-modal" id="add-modal">
    <div class="form">
        <form action="" method="post">
            {% csrf_token %}
            <h3>Add Note</h3>
            {{form | crispy}}
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Save</button>
                <button type="button" class="btn btn-danger close-btn" onclick="closeModal('add-modal')">Cancel</button>
            </div>
        </form>
    </div>
</div>
{% endblock body %}

noteapp/templates/noteapp/delete.html
{% extends '../base/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <div class="container">
       <div class="form">
            <h3 class="text-primary">Delete Note</h3>
            <p>Are you sure you want to delete this note?</p>
            <form action="" method="post">
                {% csrf_token %}
                <input type="submit" value="Delete">
            </form>
       </div>
    </div>
{% endblock body %}

noteapp/templates/noteapp/home.html
{% extends '../base/base.html' %}
{% load crispy_forms_tags %}

{% block body %}   
    <div class="container">
        <br>
        <h1>Recent Notes</h1>
        <!-- <a class="nav-link add" href="/addnote/">+ Add notes</a> -->
        <div class="notes">
            {% csrf_token %}
            {% for note in notes %}
            <div class="note">
                <h2 class="text-info">{{note.notes_title}}</h2>
                <p>{{note.note_text}}</p>
                <h6 class="text-info">{{note.Created_on}}</h6>
                <div class="options">
                    <a href="/update/{{note.id}}/" class="btn btn-success">Update</a>
                    <a href="/delete/{{note.id}}/" class="btn btn-danger">Delete</a>
                </div>
            </div>
            {% endfor %}
                
        </div>
    </div>
    <div class="add-modal" id="add-modal">
        <div class="form">
            <form action="" method="post">
                {% csrf_token %}
                <h3>Add Note</h3>
                {{form | crispy}}
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <button type="button" class="btn btn-danger close-btn" onclick="closeModal('add-modal')">Cancel</button>
                </div>
            </form>
        </div>
    </div>

{% endblock body %}    

noteapp/templates/noteapp/index.html
{% extends '../base/base.html' %}


{% block body %}
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
          <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Keep Notes</h1>
            <p class="lead text-muted">This is a note keeping app built with Django</p>
            <p>
              <a href="{% url 'noteapp:register' %}" class="btn btn-primary my-2">Create an account</a>
              <a href="{% url 'noteapp:login' %}" class="btn btn-secondary my-2">Login</a>
            </p>
          </div>
        </div>
      </section>
{% endblock body %}      

noteapp/templates/noteapp/loggedout.html
{% extends '../base/base.html' %}
    
{% block body %}

        
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
          <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">You have Logged Out</h1>
            <p class="lead text-muted">Thank you for spending quality time on the website</p>
            <p>
              <a href="{% url 'noteapp:login' %}" class="btn btn-secondary my-2">Login Again</a>
            </p>
          </div>
        </div>
      </section>
        
{% endblock body %}

noteapp/templates/noteapp/login.html
{% extends '../base/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
    

    
    <div class="container">
        <div class="form">
            
            {% if messages %}
                
                {% for message in messages %}
                    <p class="alert alert-{{message.tags}}">{{message}}</p>
                {% endfor %}
                    
                
            {% endif %}
                
            <h3 class="text-primary">Login</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form | crispy }}
                <button type="submit" class="btn-info btn">Login</button>
            </form>
    </div>
    </div>

{% endblock body %}

noteapp/templates/noteapp/register.html
{% extends '../base/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <div class="container">
        <div class="form">
            <h3 class="text-primary">Sign Up</h3>
            <form action="" method="POST">
                {% csrf_token %}              
                {{form | crispy}}               
                <button type="submit" class="btn-info btn">Sign up</button>
            </form>
    </div>
    </div>
{% endblock body %}

noteapp/templates/noteapp/settings.html
{% extends '../base/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <div class="container">
        <div class="form">
            <h3 class="text-primary">Account Settings</h3>
            {% if messages %}
                
                {% for message in messages %}
                    <p class="alert alert-{{message.tags}}">{{message}}</p>
                {% endfor %}
                    
                
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                {{form | crispy}}
                <button type="submit" class="btn-info btn">Save</button>
            </form>
    </div>
    </div>
{% endblock body %}

noteapp/templates/noteapp/update.html
{% extends '../base/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <div class="container">
       <div class="form">
            <h3 class="text-primary">Update Note</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form | crispy}}
                <button type="submit" class="btn-info btn">Update</button>
            </form>
       </div>
    </div>
{% endblock body %}